import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/Hero";
import Posts, { mockData } from "../components/Posts";
import useUser from "../lib/useUser";

const Home: NextPage = () => {
  const user = useUser();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero />
        <Posts blogPosts={mockData} />
      </div>
    </>
  );
};

export default Home;
